---
apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: spring-amq
  namespace: amq-demo
spec:
  version: 7.8.1
  deploymentPlan:
    size: 1
    image: placeholder
    requireLogin: false
  upgrades:
    enabled: false
---
apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: spring-amq-fruits
  namespace: amq-demo
spec:
  addressName: fruits
  queueName: fruits
  routingType: anycast